apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: personal-portfolio
  description: My personal portfolio site hosted on Netlify
  tags:
    - portfolio
spec:
  type: website
  lifecycle: production
  owner: anamol_soman
  system: personal
  repository: https://github.com/anamolsoman/my-portfolio
